services:
  gotenberg:
    image: gotenberg/gotenberg:8.31.0
    ports:
      - "3001:3000"
    command:
      - "gotenberg"
      - "--chromium-ignore-certificate-errors"
      - "--api-timeout=30s"
      - "--pdfengines-engines=pdftk"
      - "--uno-listener-restart-threshold=0"