process.env.FEATURE_FLAG_WRITE_DISABLED = 'true'
process.env.DD_V5_1_ENABLED = 'false'
process.env.MAPPA_ENABLED = 'true'
process.env.MONITORING_CONDITION_TIMES_ENABLED = 'false'
process.env.VARIATIONS_ENABLED = 'true'
