---
# Per environment values which override defaults in hmpps-electronic-monitoring-create-an-order/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: hmpps-electronic-monitoring-create-an-order-dev.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://hmpps-electronic-monitoring-create-an-order-dev.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    ENVIRONMENT_NAME: DEV
    AUDIT_ENABLED: "false"
    REDIS_HOST: "no_value"
    REDIS_AUTH_TOKEN: "no_value"

generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev