---
# Per environment values which override defaults in hmpps-electronic-monitoring-create-an-order/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: hmpps-electronic-monitoring-create-an-order-dev.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://hmpps-electronic-monitoring-create-an-order-dev.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    CEMO_API_URL: "https://hmpps-electronic-monitoring-create-an-order-api-dev.hmpps.service.justice.gov.uk"
    ENVIRONMENT_NAME: DEV
    AUDIT_ENABLED: "false"
    DD_V5_1_ENABLED: "false"
    ALCOHOL_MONITORING_ENABLED: "true"
    TAG_AT_SOURCE_PILOT_PRISONS: "PETERBOROUGH_PRISON,FOSSE_WAY_PRISON,SUDBURY_PRISON,RANBY_PRISON,SWANSEA_PRISON,CARDIFF_PRISON"    

  allowlist:
    unrestricted: "0.0.0.0/0"

generic-prometheus-alerts:
  alertSeverity: hmpps-electronic-monitoring-create-an-order-dev
