const paths = {
  ORDER: {
    BASE_URL: '/order/:orderId',
    CREATE: '/order/create',
    DELETE: '/order/:orderId/delete',
    DELETE_FAILED: '/order/delete/failed',
    DELETE_SUCCESS: '/order/delete/success',
    SUMMARY: '/order/:orderId/summary',
    SUMMARY_VERSION: '/order/:orderId/version/:versionId/summary',
    SUBMIT: '/order/:orderId/submit',
    SUBMIT_FAILED: '/order/:orderId/submit/failed',
    SUBMIT_PARTIAL_SUCCESS: '/order/:orderId/submit/partial-success',
    SUBMIT_SUCCESS: '/order/:orderId/submit/success',
    RECEIPT: '/order/:orderId/receipt',
    RECEIPT_VERSION: '/order/:orderId/version/:versionId/receipt',
    RECEIPT_DOWNLOAD: '/order/:orderId/pdf',
    DOWNLOAD_FMS_DW_REQUEST: '/order/:orderId/fmsDeviceWearerRequests',
    DOWNLOAD_FMS_MO_REQUEST: '/order/:orderId/fmsMonitoringOrderRequests',
    EDIT: '/order/:orderId/edit',
    IS_REJECTION: '/order/:orderId/is-rejection',
    VARIATION: '/order/:orderId/variation',
  },

  ABOUT_THE_DEVICE_WEARER: {
    CHECK_YOUR_ANSWERS: '/order/:orderId/about-the-device-wearer/check-your-answers',
    CHECK_YOUR_ANSWERS_VERSION: '/order/:orderId/version/:versionId/about-the-device-wearer/check-your-answers',
    DEVICE_WEARER: '/order/:orderId/about-the-device-wearer',
    RESPONSIBLE_ADULT: '/order/:orderId/about-the-device-wearer/responsible-adult',
    IDENTITY_NUMBERS: '/order/:orderId/about-the-device-wearer/identity-numbers',
  },

  CONTACT_INFORMATION: {
    CHECK_YOUR_ANSWERS: '/order/:orderId/contact-information/check-your-answers',
    CHECK_YOUR_ANSWERS_VERSION: '/order/:orderId/version/:versionId/contact-information/check-your-answers',
    CONTACT_DETAILS: '/order/:orderId/contact-information/contact-details',
    NO_FIXED_ABODE: '/order/:orderId/contact-information/no-fixed-abode',
    ADDRESSES: '/order/:orderId/contact-information/addresses/:addressType(primary|secondary|tertiary)',
    INTERESTED_PARTIES: '/order/:orderId/contact-information/interested-parties',
    PROBATION_DELIVERY_UNIT: '/order/:orderId/contact-information/probation-delivery-unit',
  },

  INSTALLATION_AND_RISK: {
    INSTALLATION_AND_RISK: '/order/:orderId/installation-and-risk',
    CHECK_YOUR_ANSWERS: '/order/:orderId/installation-and-risk/check-your-answers',
    CHECK_YOUR_ANSWERS_VERSION: '/order/:orderId/version/:versionId/installation-and-risk/check-your-answers',
    BASE_URL: '/order/:orderId/installation-and-risk',
    OFFENCE: '/order/:orderId/installation-and-risk/offence',
    OFFENCE_OTHER_INFO: '/order/:orderId/installation-and-risk/offence-other-info',
    OFFENCE_LIST: '/order/:orderId/installation-and-risk/offence-list',
    DAPO: '/order/:orderId/installation-and-risk/dapo',
    DAPO_ID: '/order/:orderId/installation-and-risk/dapo/:clauseId',
    DELETE: '/order/:orderId/installation-and-risk/delete',
  },

  POSTCODE_LOOKUP: {
    FIND_ADDRESS: '/order/:orderId/find-address/:addressType',
    ADDRESS_RESULT: '/order/:orderId/address-result/:addressType',
    CONFIRM_ADDRESS: '/order/:orderId/confirm-address/:addressType',
    ENTER_ADDRESS: '/order/:orderId/enter-address/:addressType',
    ADDRESS_LIST: '/order/:orderId/address-list',
  },

  MONITORING_CONDITIONS: {
    INSTALLATION_LOCATION: '/order/:orderId/monitoring-conditions/installation-location',
    INSTALLATION_APPOINTMENT: '/order/:orderId/monitoring-conditions/installation-appointment',
    INSTALLATION_ADDRESS: '/order/:orderId/monitoring-conditions/:addressType(installation)',
    TRAIL: '/order/:orderId/monitoring-conditions/trail',
    ZONE: '/order/:orderId/monitoring-conditions/zone/:zoneId',
    ZONE_NEW_ITEM: '/order/:orderId/monitoring-conditions/add-to-list/zone',
    ZONE_ADD_TO_LIST: '/order/:orderId/monitoring-conditions/add-to-list/zone/:zoneId',
    ATTENDANCE: '/order/:orderId/monitoring-conditions/attendance',
    ATTENDANCE_ADD_TO_LIST: '/order/:orderId/monitoring-conditions/add-to-list/attendance',
    ATTENDANCE_ITEM: '/order/:orderId/monitoring-conditions/attendance/:conditionId',
    ATTENDANCE_ITEM_ADD_TO_LIST: '/order/:orderId/monitoring-conditions/add-to-list/attendance/:conditionId',
    ALCOHOL: '/order/:orderId/monitoring-conditions/alcohol',
    CURFEW_RELEASE_DATE: '/order/:orderId/monitoring-conditions/curfew/release-date',
    CURFEW_CONDITIONS: '/order/:orderId/monitoring-conditions/curfew/conditions',
    CURFEW_ADDITIONAL_DETAILS: '/order/:orderId/monitoring-conditions/curfew/additional-details',
    CURFEW_TIMETABLE: '/order/:orderId/monitoring-conditions/curfew/timetable',
    CHECK_YOUR_ANSWERS: '/order/:orderId/monitoring-conditions/check-your-answers',
    CHECK_YOUR_ANSWERS_VERSION: '/order/:orderId/version/:versionId/monitoring-conditions/check-your-answers',
    REMOVE_MONITORING_TYPE: '/order/:orderId/monitoring-condtions/remove-monitoring-type/:monitoringTypeId',
    ORDER_TYPE_DESCRIPTION: {
      BASE_PATH: '/order/:orderId/monitoring-conditions/order-type-description',
      ORDER_TYPE: '/order/:orderId/monitoring-conditions/order-type-description/order-type',
      SENTENCE_TYPE: '/order/:orderId/monitoring-conditions/order-type-description/sentence-type',
      HDC: '/order/:orderId/monitoring-conditions/order-type-description/hdc',
      ISSP: '/order/:orderId/monitoring-conditions/order-type-description/issp',
      PRARR: '/order/:orderId/monitoring-conditions/order-type-description/prarr',
      POLICE_AREA: '/order/:orderId/monitoring-conditions/order-type-description/police-area',
      PILOT: '/order/:orderId/monitoring-conditions/order-type-description/pilot',
      DAPOL_MISSED_IN_ERROR: '/order/:orderId/monitoring-conditions/order-type-description/dapol-missed-in-error',
      MONITORING_TYPES: '/order/:orderId/monitoring-conditions/order-type-description/monitoring-types',
      MONITORING_TYPE: '/order/:orderId/monitoring-conditions/order-type-description/monitoring-type',
      TYPES_OF_MONITORING_NEEDED:
        '/order/:orderId/monitoring-conditions/order-type-description/types-of-monitoring-needed',
      OFFENCE_TYPE: '/order/:orderId/monitoring-conditions/order-type-description/offence-type',
      HARD_STOP: '/order/:orderId/monitoring-conditions/order-type-description/hard-stop',
    },
  },

  ATTACHMENT: {
    ATTACHMENTS: '/order/:orderId/attachments',
    ATTACHMENTS_VERSION: '/order/:orderId/version/:versionId/attachments',
    FILE_VIEW: '/order/:orderId/attachments/:fileType(photo_Id|licence|court_order|grant_of_bail)',
    DOWNLOAD_FILE: '/order/:orderId/attachments/:fileType(photo_Id|licence|court_order|grant_of_bail)/:filename',
    DELETE_FILE: '/order/:orderId/attachments/:fileType(photo_Id|licence|court_order|grant_of_bail)/delete',
    HAVE_PHOTO: '/order/:orderId/attachments/have-photo',
    HAVE_COURT_ORDER: '/order/:orderId/attachments/have-court-order',
    HAVE_GRANT_OF_BAIL: '/order/:orderId/attachments/have-grant-of-bail',
  },

  VARIATION: {
    VARIATION_DETAILS: '/order/:orderId/variation/details',
    VARIATION_DETAILS_VERSION: '/order/:orderId/version/:versionId/variation/details',
    SERVICE_REQUEST_TYPE: '/order/:orderId/service-request-type',
    CREATE_VARIATION: '/order/create-variation',
  },
}

export default paths
